### ISSUE TITLE
Get styles with no parameters.

### ISSUE THREAD

**Issue by gagoar** [benmvp/dom-info#2]
``` js
var getStyle = require('dom-info/getStyle');

var node = document.getElementById('node'),
    allAvailableStyles = getStyle('', node);
```

**Comment by benmvp** [comment]
Yep, this makes sense. I think right now this will return an empty string, but returning all the styles should work. It'd be _slow_, but it should work

**Comment by benmvp** [comment]
This is now implemented in PR #4 and it shouldn't be _that_ slow.

**Comment by benmvp** [comment]
Merged!

**Comment by gagoar** [comment]
I understand that the reference  you copied in the `reduce` aims to avoid transformation (at least in the syntax) but sadly this is not trivial to do in es3-5 (other than for-in per key) and transformation happens anyways. 

I analyzed the side effect of this and arguably could be a penalty with the garbage collector implementation given that every reference might prevent the object to be collected. 

Again a correct implementation would work fine, given that the scope of the function is short lived, but better be safe than sorry.
